import fs from "fs";
import path from "path";

const GENERATED_BY = "pokie certification build";

// Certification has the same whole-container publication contract as Stake:
// only a prior POKIE publication may be replaced, except for the longstanding
// explicit empty destination workflow. Do not
// follow symlinks here; a caller's link is an external destination regardless
// of what happens to be at its target.
export function assertSafeToReplaceCertificationEvidenceDirectory(outDir: string): void {
    let destination: fs.Stats;
    try {
        destination = fs.lstatSync(outDir);
    } catch (error) {
        if ((error as NodeJS.ErrnoException).code === "ENOENT") return;
        throw error;
    }

    if (destination.isSymbolicLink()) {
        throw new Error(`"${outDir}" is a symbolic link, not a POKIE-owned certification/evidence output directory. Choose a different --out directory.`);
    }
    if (!destination.isDirectory()) {
        throw new Error(`"${outDir}" already exists and is not a directory. Choose a different --out directory or remove it first.`);
    }
    if (fs.readdirSync(outDir).length === 0) return;
    if (!isRecognizedCertificationEvidenceDirectory(outDir)) {
        throw new Error(
            `"${outDir}" already exists and was not generated by "pokie certification build" (no recognized manifest.json). ` +
            "Refusing to replace it wholesale — choose a different --out directory, empty it first, or point --out at a directory " +
            'previously produced by "pokie certification build".',
        );
    }
}

function isRecognizedCertificationEvidenceDirectory(outDir: string): boolean {
    try {
        const manifest = JSON.parse(fs.readFileSync(path.join(outDir, "manifest.json"), "utf-8")) as {generatedBy?: unknown};
        return manifest.generatedBy === GENERATED_BY;
    } catch {
        return false;
    }
}
