// ============================================================================
// GENERATED FILE — do not hand-edit.
//
// Produced by "pokie build" from a GameBlueprint JSON config. Re-run "pokie build" (see this
// package's README.md) to regenerate this file after changing the blueprint; any manual edits here
// are overwritten on the next run.
//
// Game: Opulent Gilded Payout (id: "opulent-gilded-payout", version 0.1.0)
// Generated by: pokie 1.3.0
// ============================================================================

import type {GameBlueprint, PokieGameContext} from "pokie";

// ---------------------------------------------------------------------------
// pokie runtime
// ---------------------------------------------------------------------------
const {
    CustomLinesDefinitions,
    ReelsSymbolsSequencesGenerator,
    SeededRandomNumberGenerator,
    SymbolsCombinationsGenerator,
    SymbolsSequence,
    VideoSlotConfig,
    VideoSlotSession,
    VideoSlotSessionSerializer,
    computeGameBlueprintHash,
} = require("pokie");

// ---------------------------------------------------------------------------
// Blueprint data (embedded verbatim from the source GameBlueprint JSON config)
// ---------------------------------------------------------------------------
const blueprint: GameBlueprint = {
    "manifest": {
        "id": "opulent-gilded-payout",
        "name": "Opulent Gilded Payout",
        "version": "0.1.0",
        "description": "Randomly generated video slot (seed 1194709122)."
    },
    "reels": 4,
    "rows": 4,
    "symbols": [
        "Q",
        "7",
        "8",
        "J",
        "A",
        "9",
        "10"
    ],
    "paytable": {
        "7": {
            "3": 6,
            "4": 12
        },
        "8": {
            "3": 5,
            "4": 10
        },
        "9": {
            "3": 2,
            "4": 4
        },
        "10": {
            "3": 1,
            "4": 2
        },
        "Q": {
            "3": 7,
            "4": 14
        },
        "J": {
            "3": 4,
            "4": 8
        },
        "A": {
            "3": 3,
            "4": 6
        }
    },
    "availableBets": [
        1,
        2,
        5,
        10
    ],
    "reelStrips": [
        [
            "J",
            "J",
            "A",
            "A",
            "9",
            "9",
            "7",
            "9",
            "9",
            "9",
            "8",
            "10",
            "J",
            "9",
            "Q",
            "J",
            "10",
            "7",
            "A",
            "8",
            "10",
            "10",
            "10",
            "8",
            "10",
            "A",
            "A",
            "10"
        ],
        [
            "A",
            "J",
            "J",
            "J",
            "10",
            "9",
            "7",
            "10",
            "J",
            "8",
            "10",
            "8",
            "8",
            "A",
            "A",
            "A",
            "9",
            "Q",
            "9",
            "10",
            "10",
            "10",
            "9",
            "7",
            "9",
            "10",
            "A",
            "9"
        ],
        [
            "A",
            "7",
            "10",
            "10",
            "J",
            "J",
            "J",
            "7",
            "9",
            "10",
            "A",
            "10",
            "A",
            "9",
            "8",
            "10",
            "9",
            "10",
            "A",
            "9",
            "9",
            "8",
            "Q",
            "A",
            "8",
            "9",
            "J",
            "10"
        ],
        [
            "A",
            "9",
            "8",
            "A",
            "9",
            "J",
            "10",
            "7",
            "A",
            "9",
            "8",
            "10",
            "A",
            "10",
            "9",
            "A",
            "7",
            "10",
            "J",
            "10",
            "8",
            "10",
            "9",
            "9",
            "10",
            "J",
            "J",
            "Q"
        ]
    ]
};

// ---------------------------------------------------------------------------
// VideoSlotConfig assembly
//
// Setter order matters here: setAvailableBets/setWildSymbols/setScatterSymbols must run before
// setAvailableSymbols, which rebuilds the paytable and (absent explicit reel strips) the default
// reel sequences from whatever wilds/scatters are set at that point. The paytable, paylines, and
// reel strips are set after setAvailableSymbols, since it would otherwise overwrite them. See
// VideoSlotConfig for the full contract.
//
// "context" (present only to read context.seed) makes every random choice this function itself makes
// -- VideoSlotConfig's own default reel-strip shuffle (absent explicit reelStrips/symbolWeights) and
// the symbolWeights branch's own shuffle() below -- deterministic for a given seed, the same as
// createSession's own combinationsGenerator (see the "combinationsGeneratorDeclaration" this function
// is called from). A blueprint with literal blueprint.reelStrips needs none of this: it never calls
// shuffle() at all.
// ---------------------------------------------------------------------------
function createConfig(context?: PokieGameContext) {
    const reelStripRng = context && context.seed !== undefined ? new SeededRandomNumberGenerator(context.seed) : undefined;
    const config = new VideoSlotConfig(undefined, reelStripRng ? new ReelsSymbolsSequencesGenerator(reelStripRng) : undefined);

    if (blueprint.availableBets) {
        config.setAvailableBets(blueprint.availableBets);
    }
    config.setReelsNumber(blueprint.reels);
    config.setReelsSymbolsNumber(blueprint.rows);
    config.setWildSymbols(blueprint.wilds || []);
    config.setScatterSymbols(blueprint.scatters || []);
    config.setAvailableSymbols(blueprint.symbols);

    const paytable = config.getPaytable();
    for (const symbolId of Object.keys(blueprint.paytable)) {
        const payouts = blueprint.paytable[symbolId];
        for (const times of Object.keys(payouts)) {
            paytable.setPayoutForSymbol(symbolId, Number(times), payouts[times]);
        }
    }

    if (blueprint.paylines) {
        const linesDefinitions = new CustomLinesDefinitions();
        blueprint.paylines.forEach((line, index) => linesDefinitions.setLineDefinition(String(index), line));
        config.setLinesDefinitions(linesDefinitions);
    }

    if (blueprint.reelStrips) {
        config.setSymbolsSequences(blueprint.reelStrips.map((strip) => new SymbolsSequence().fromArray(strip)));
    } else if (blueprint.symbolWeights) {
        const sequences = [];
        for (let i = 0; i < blueprint.reels; i++) {
            sequences.push(new SymbolsSequence().fromNumbersOfSymbols(blueprint.symbolWeights).shuffle(reelStripRng));
        }
        config.setSymbolsSequences(sequences);
    }

    return config;
}

// ---------------------------------------------------------------------------
// PokieGame contract (see docs/game-packages.md)
// ---------------------------------------------------------------------------
module.exports = {
    getManifest() {
        return blueprint.manifest;
    },
    createSession(context?: PokieGameContext) {
        const config = createConfig(context);
        const combinationsGenerator = context && context.seed !== undefined
            ? new SymbolsCombinationsGenerator(config, new SeededRandomNumberGenerator(context.seed))
            : new SymbolsCombinationsGenerator(config);
        return new VideoSlotSession(config, combinationsGenerator);
    },
    getSessionSerializer() {
        return new VideoSlotSessionSerializer();
    },
    getConfigHash() {
        return computeGameBlueprintHash(blueprint);
    },
    createExactEnumerationSession(combinationsGenerator: unknown) {
        const config = createConfig();
        return new VideoSlotSession(config, combinationsGenerator);
    },
};
