import fs from "fs";
import path from "path";
import type {StudioJobRepository} from "./StudioJobRepository.js";
import type {StudioJobView} from "./StudioJobView.js";

/**
 * A small append-free store: each record is independently atomically replaced,
 * which avoids one large jobs file becoming a contention point or losing every
 * retained result when a machine is interrupted during one write.
 */
export class FileStudioJobRepository implements StudioJobRepository {
    private readonly directory: string;
    private readonly retention: number;

    public constructor(directory: string, retention = 100) {
        this.directory = directory;
        this.retention = retention;
    }

    public list(projectId?: string): readonly StudioJobView[] {
        let entries: readonly fs.Dirent[];
        try {
            entries = fs.readdirSync(this.directory, {withFileTypes: true});
        } catch {
            return [];
        }
        const jobs: StudioJobView[] = [];
        for (const entry of entries) {
            if (!entry.isFile() || !entry.name.endsWith(".json")) continue;
            const job = this.read(path.join(this.directory, entry.name));
            if (job !== undefined && (projectId === undefined || job.projectId === projectId)) {
                jobs.push(job);
            }
        }
        return jobs.sort((left, right) => right.createdAt - left.createdAt);
    }

    public get(id: string): StudioJobView | undefined {
        return this.read(this.pathFor(id));
    }

    public save(job: StudioJobView): void {
        fs.mkdirSync(this.directory, {recursive: true});
        const destination = this.pathFor(job.id);
        const temporary = `${destination}.${process.pid}.${Date.now()}.tmp`;
        fs.writeFileSync(temporary, JSON.stringify(job), "utf8");
        fs.renameSync(temporary, destination);
        this.trim();
    }

    public remove(id: string): void {
        try {
            fs.unlinkSync(this.pathFor(id));
        } catch (error) {
            if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
        }
    }

    private read(filePath: string): StudioJobView | undefined {
        try {
            const value: unknown = JSON.parse(fs.readFileSync(filePath, "utf8"));
            return isJob(value) ? value : undefined;
        } catch {
            return undefined;
        }
    }

    private pathFor(id: string): string {
        // IDs are generated by this service.  Still reject separators here so a
        // malformed/corrupt route parameter can never escape the store.
        if (!(/^[A-Za-z0-9_-]+$/).test(id)) throw new Error("Invalid Studio job id.");
        return path.join(this.directory, `${id}.json`);
    }

    private trim(): void {
        const terminal = this.list().filter((job) => job.status !== "queued" && job.status !== "running" && job.status !== "cancelling");
        for (const job of terminal.slice(this.retention)) this.remove(job.id);
    }
}

function isJob(value: unknown): value is StudioJobView {
    if (typeof value !== "object" || value === null) return false;
    const job = value as Partial<StudioJobView>;
    return typeof job.id === "string" && (/^[A-Za-z0-9_-]+$/).test(job.id)
        && typeof job.projectId === "string" && typeof job.operation === "string"
        && typeof job.conflictKey === "string" && typeof job.status === "string"
        && typeof job.createdAt === "number" && typeof job.request === "object" && job.request !== null;
}
