// Every Node.js built-in module name scanForBlockingNodeApiUsage checks an import/require specifier against,
// after stripping an optional leading "node:" -- deliberately the module names only (no submodule paths like
// "fs/promises", which already start with a name in this set and are caught by scanForBlockingNodeApiUsage's
// own specifier-splitting). Not exhaustive of every Node release's own builtins, but covers every one a real
// game package/CLI dependency plausibly reaches for.
export const NODE_BUILTIN_MODULES: ReadonlySet<string> = new Set([
    "assert",
    "async_hooks",
    "buffer",
    "child_process",
    "cluster",
    "crypto",
    "dgram",
    "diagnostics_channel",
    "dns",
    "domain",
    "events",
    "fs",
    "http",
    "http2",
    "https",
    "inspector",
    "module",
    "net",
    "os",
    "path",
    "perf_hooks",
    "process",
    "punycode",
    "querystring",
    "readline",
    "repl",
    "stream",
    "string_decoder",
    "sys",
    "timers",
    "tls",
    "trace_events",
    "tty",
    "url",
    "util",
    "v8",
    "vm",
    "worker_threads",
    "zlib",
]);
