import {GamePackageInspecting, GamePackageInspectionReport, GamePackageInspector} from "pokie";
import {CliCommandHandling} from "../CliCommandHandling.js";

const USAGE = "Usage: pokie inspect <packageRoot>";

export class InspectCommand implements CliCommandHandling {
    private readonly inspector: GamePackageInspecting;

    constructor(inspector: GamePackageInspecting = new GamePackageInspector()) {
        this.inspector = inspector;
    }

    public getName(): string {
        return "inspect";
    }

    public getDescription(): string {
        return 'Print a package\'s provenance (game, blueprint hash, source, "pokie build" version) from package.json and src/generated/build-info.json, without running it.';
    }

    public run(args: string[]): Promise<number> {
        const [packageRoot, ...rest] = args;
        if (!packageRoot) {
            return Promise.reject(new Error(USAGE));
        }
        if (rest.length > 0) {
            return Promise.reject(new Error(`Unknown option "${rest[0]}". ${USAGE}`));
        }

        const report = this.inspector.inspect(packageRoot);
        this.print(report);
        return Promise.resolve(report.valid ? 0 : 1);
    }

    private print(report: GamePackageInspectionReport): void {
        if (!report.valid) {
            console.error(report.error);
            return;
        }

        console.log(`Inspecting package at "${report.packageRoot}"\n`);

        if (report.buildInfo) {
            const {buildInfo} = report;
            console.log(`  game             ${buildInfo.game.name} (id: "${buildInfo.game.id}", v${buildInfo.game.version})`);
            console.log(`  package root     ${report.packageRoot}`);
            console.log(`  blueprint hash   ${buildInfo.blueprintHash}`);
            console.log(`  source           ${buildInfo.source ?? "(unknown)"}`);
            console.log(`  generated at     ${buildInfo.generatedAt}`);
            console.log(`  pokie version    ${buildInfo.pokieVersion}`);
            console.log(`  generated files  ${(buildInfo.files ?? []).join(", ")}`);
            return;
        }

        console.log(`  package.json     name: "${report.packageJson?.name ?? "(unknown)"}", version: "${report.packageJson?.version ?? "(unknown)"}"`);
        console.log(`\nThis package does not look like it was generated by "pokie build" (no src/generated/build-info.json found).`);
    }
}
