import {GamePackageInspecting, GamePackageInspectionReport, GamePackageInspector} from "pokie";
import fs from "fs";
import os from "os";
import path from "path";
import {BuildCommand} from "../../../cli/commands/BuildCommand.js";
import {InspectCommand} from "../../../cli/commands/InspectCommand.js";

function createStubInspector(report: GamePackageInspectionReport): GamePackageInspecting & {calledWith?: string} {
    return {
        inspect(packageRoot: string) {
            this.calledWith = packageRoot;
            return report;
        },
    };
}

const generatedReport: GamePackageInspectionReport = {
    packageRoot: "./crazy-fruits",
    valid: true,
    generated: true,
    packageJson: {name: "crazy-fruits", version: "0.1.0"},
    buildInfo: {
        schemaVersion: 1,
        generatedBy: "pokie build",
        pokieVersion: "1.3.0",
        generatedAt: "2026-01-02T03:04:05.000Z",
        blueprintHash: "sha256:abc123",
        source: "crazy-fruits.blueprint.json",
        files: ["README.md", "package.json", "src/generated/build-info.json", "src/generated/index.js"],
        game: {id: "crazy-fruits", name: "Crazy Fruits", version: "0.1.0"},
    },
};

const notGeneratedReport: GamePackageInspectionReport = {
    packageRoot: "./hand-written",
    valid: true,
    generated: false,
    packageJson: {name: "hand-written", version: "1.0.0"},
};

const invalidReport: GamePackageInspectionReport = {
    packageRoot: "./missing",
    valid: false,
    generated: false,
    error: '"./missing" does not exist or is not a directory.',
};

describe("InspectCommand", () => {
    let logSpy: jest.SpyInstance;
    let errorSpy: jest.SpyInstance;

    beforeEach(() => {
        logSpy = jest.spyOn(console, "log").mockImplementation(() => undefined);
        errorSpy = jest.spyOn(console, "error").mockImplementation(() => undefined);
    });

    afterEach(() => {
        logSpy.mockRestore();
        errorSpy.mockRestore();
    });

    it("has the expected name and description", () => {
        const command = new InspectCommand(createStubInspector(generatedReport));

        expect(command.getName()).toBe("inspect");
        expect(command.getDescription().length).toBeGreaterThan(0);
    });

    it("throws when run without a packageRoot", async () => {
        const command = new InspectCommand(createStubInspector(generatedReport));

        await expect(command.run([])).rejects.toThrow(/Usage: pokie inspect <packageRoot>/);
    });

    it("throws a descriptive error for an unexpected extra argument", async () => {
        const command = new InspectCommand(createStubInspector(generatedReport));

        await expect(command.run(["./game", "--bogus"])).rejects.toThrow(/Unknown option "--bogus"/);
    });

    it("passes the given packageRoot to the inspector", async () => {
        const inspector = createStubInspector(generatedReport);
        const command = new InspectCommand(inspector);

        await command.run(["./crazy-fruits"]);

        expect(inspector.calledWith).toBe("./crazy-fruits");
    });

    it("prints game/hash/source/timestamp/pokie version/files and returns 0 for a generated package", async () => {
        const command = new InspectCommand(createStubInspector(generatedReport));

        const exitCode = await command.run(["./crazy-fruits"]);

        expect(exitCode).toBe(0);
        const printed = logSpy.mock.calls.map((call) => call[0]).join("\n");
        expect(printed).toContain('Inspecting package at "./crazy-fruits"');
        expect(printed).toContain('game             Crazy Fruits (id: "crazy-fruits", v0.1.0)');
        expect(printed).toContain("package root     ./crazy-fruits");
        expect(printed).toContain("blueprint hash   sha256:abc123");
        expect(printed).toContain("source           crazy-fruits.blueprint.json");
        expect(printed).toContain("generated at     2026-01-02T03:04:05.000Z");
        expect(printed).toContain("pokie version    1.3.0");
        expect(printed).toContain("generated files  README.md, package.json, src/generated/build-info.json, src/generated/index.js");
    });

    it("prints a clear not-generated message and returns 0 for a package with no build-info.json", async () => {
        const command = new InspectCommand(createStubInspector(notGeneratedReport));

        const exitCode = await command.run(["./hand-written"]);

        expect(exitCode).toBe(0);
        const printed = logSpy.mock.calls.map((call) => call[0]).join("\n");
        expect(printed).toContain('package.json     name: "hand-written", version: "1.0.0"');
        expect(printed).toContain('does not look like it was generated by "pokie build"');
        expect(printed).not.toContain("blueprint hash");
    });

    it("prints the error and returns 1 for an invalid/missing package root", async () => {
        const command = new InspectCommand(createStubInspector(invalidReport));

        const exitCode = await command.run(["./missing"]);

        expect(exitCode).toBe(1);
        expect(errorSpy).toHaveBeenCalledWith(invalidReport.error);
        expect(logSpy).not.toHaveBeenCalled();
    });
});

describe("InspectCommand (integration, real GamePackageInspector)", () => {
    let logSpy: jest.SpyInstance;
    let errorSpy: jest.SpyInstance;

    beforeEach(() => {
        logSpy = jest.spyOn(console, "log").mockImplementation(() => undefined);
        errorSpy = jest.spyOn(console, "error").mockImplementation(() => undefined);
    });

    afterEach(() => {
        logSpy.mockRestore();
        errorSpy.mockRestore();
    });

    it("inspects a real package generated by \"pokie build\" and returns 0", async () => {
        const workDir = fs.mkdtempSync(path.join(os.tmpdir(), "pokie-inspect-workflow-test-"));
        const outDir = path.join(workDir, "built-game");
        const blueprintPath = path.join(__dirname, "..", "..", "..", "examples", "blueprints", "crazy-fruits.blueprint.json");
        try {
            const buildExitCode = await new BuildCommand("1.3.0").run([blueprintPath, "--out", outDir]);
            expect(buildExitCode).toBe(0);
            logSpy.mockClear();

            const command = new InspectCommand(new GamePackageInspector());
            const exitCode = await command.run([outDir]);

            expect(exitCode).toBe(0);
            const printed = logSpy.mock.calls.map((call) => call[0]).join("\n");
            expect(printed).toContain('game             Crazy Fruits (id: "crazy-fruits", v0.1.0)');
            expect(printed).toContain("blueprint hash   sha256:");
            expect(printed).toContain(`source           ${blueprintPath}`);
        } finally {
            fs.rmSync(workDir, {recursive: true, force: true});
        }
    });

    it("inspects a real hand-written (non-generated) package and returns 0 with a clear message", async () => {
        const packageRoot = path.join(__dirname, "..", "..", "gamepackage", "fixtures", "valid-game");
        const command = new InspectCommand(new GamePackageInspector());

        const exitCode = await command.run([packageRoot]);

        expect(exitCode).toBe(0);
        const printed = logSpy.mock.calls.map((call) => call[0]).join("\n");
        expect(printed).toContain('package.json     name: "valid-game", version: "1.0.0"');
        expect(printed).toContain('does not look like it was generated by "pokie build"');
    });

    it("returns 1 for a missing package root", async () => {
        const command = new InspectCommand(new GamePackageInspector());

        const exitCode = await command.run([path.join(os.tmpdir(), "definitely-does-not-exist-pokie-inspect")]);

        expect(exitCode).toBe(1);
        expect(errorSpy).toHaveBeenCalled();
    });
});
