import {StakeEngineImportBundle, StakeEngineImportModeFiles, StakeEngineImportValidator} from "pokie";

const VALID_INDEX = {
    modes: [{name: "base", cost: 1, events: "books_base.jsonl.zst", weights: "lookup_base.csv"}],
};

const VALID_MANIFEST = {
    schemaVersion: 1,
    generatedBy: "pokie stakeengine export",
    pokieVersion: "1.3.0",
    generatedAt: "2024-01-01T00:00:00.000Z",
    game: {id: "crazy-fruits", name: "Crazy Fruits", version: "0.1.0"},
    modes: [
        {
            name: "base",
            betMode: "base",
            stake: 1,
            cost: 1,
            outcomeCount: 1,
            libraryId: "base-lib",
            libraryHash: "sha256:abc",
            events: "books_base.jsonl.zst",
            weights: "lookup_base.csv",
        },
    ],
    files: ["index.json", "pokie-manifest.json", "lookup_base.csv", "books_base.jsonl.zst"],
};

const VALID_MODE_FILES: StakeEngineImportModeFiles = {
    modeName: "base",
    csvFileExists: true,
    csvLines: ["0,1,0"],
    booksFileExists: true,
    bookLines: [{id: 0, events: [{index: 0, type: "reveal", board: [["A"]]}, {index: 1, type: "finalWin", amount: 0, payoutMultiplier: 0}], payoutMultiplier: 0}],
};

function baseBundle(): StakeEngineImportBundle {
    return {
        stakeDir: "/stake",
        indexFileExists: true,
        rawIndex: VALID_INDEX,
        manifestFileExists: true,
        rawManifest: VALID_MANIFEST,
        modeFiles: [VALID_MODE_FILES],
    };
}

function issueCodes(bundle: StakeEngineImportBundle): string[] {
    return new StakeEngineImportValidator().validate(bundle).map((issue) => issue.code);
}

describe("StakeEngineImportValidator", () => {
    it("reports no issues for a valid bundle", () => {
        expect(new StakeEngineImportValidator().validate(baseBundle())).toEqual([]);
    });

    it("reports stakeengine-import-index-missing when index.json doesn't exist", () => {
        expect(issueCodes({...baseBundle(), indexFileExists: false, rawIndex: undefined})).toEqual(["stakeengine-import-index-missing"]);
    });

    it("reports stakeengine-import-index-malformed for a missing modes array, an empty one, a bad entry, or a duplicate name", () => {
        expect(issueCodes({...baseBundle(), rawIndex: {}})).toContain("stakeengine-import-index-malformed");
        expect(issueCodes({...baseBundle(), rawIndex: {modes: []}})).toContain("stakeengine-import-index-malformed");
        expect(issueCodes({...baseBundle(), rawIndex: {modes: [{name: "base"}]}})).toContain("stakeengine-import-index-malformed");
        expect(
            issueCodes({
                ...baseBundle(),
                rawIndex: {modes: [VALID_INDEX.modes[0], VALID_INDEX.modes[0]]},
            }),
        ).toContain("stakeengine-import-index-malformed");
    });

    it("reports stakeengine-import-manifest-missing when pokie-manifest.json doesn't exist", () => {
        expect(issueCodes({...baseBundle(), manifestFileExists: false, rawManifest: undefined})).toContain("stakeengine-import-manifest-missing");
    });

    it("reports stakeengine-import-manifest-unrecognized when the manifest doesn't parse or wasn't generated by pokie stakeengine export", () => {
        expect(issueCodes({...baseBundle(), rawManifest: undefined})).toContain("stakeengine-import-manifest-unrecognized");
        expect(issueCodes({...baseBundle(), rawManifest: {generatedBy: "someone else"}})).toContain("stakeengine-import-manifest-unrecognized");
    });

    it("reports stakeengine-import-manifest-schema-version-unsupported for an unrecognized schemaVersion", () => {
        expect(issueCodes({...baseBundle(), rawManifest: {...VALID_MANIFEST, schemaVersion: 999}})).toEqual([
            "stakeengine-import-manifest-schema-version-unsupported",
        ]);
    });

    it("reports stakeengine-import-mode-missing-in-manifest when a mode in index.json has no manifest counterpart", () => {
        const bundle = baseBundle();
        expect(
            issueCodes({
                ...bundle,
                rawIndex: {modes: [...VALID_INDEX.modes, {name: "bonus", cost: 100, events: "books_bonus.jsonl.zst", weights: "lookup_bonus.csv"}]},
            }),
        ).toContain("stakeengine-import-mode-missing-in-manifest");
    });

    it("reports stakeengine-import-mode-missing-in-index when a mode in the manifest has no index.json counterpart", () => {
        expect(
            issueCodes({
                ...baseBundle(),
                rawManifest: {
                    ...VALID_MANIFEST,
                    modes: [...VALID_MANIFEST.modes, {...VALID_MANIFEST.modes[0], name: "bonus"}],
                },
            }),
        ).toContain("stakeengine-import-mode-missing-in-index");
    });

    it("reports stakeengine-import-mode-cost-mismatch when index.json and the manifest disagree on a mode's cost", () => {
        expect(
            issueCodes({
                ...baseBundle(),
                rawIndex: {modes: [{...VALID_INDEX.modes[0], cost: 2}]},
            }),
        ).toContain("stakeengine-import-mode-cost-mismatch");
    });

    it("reports stakeengine-import-mode-events-filename-mismatch when index.json and the manifest disagree on a mode's events filename", () => {
        expect(
            issueCodes({
                ...baseBundle(),
                rawIndex: {modes: [{...VALID_INDEX.modes[0], events: "books_other.jsonl.zst"}]},
            }),
        ).toContain("stakeengine-import-mode-events-filename-mismatch");
    });

    it("reports stakeengine-import-mode-weights-filename-mismatch when index.json and the manifest disagree on a mode's weights filename", () => {
        expect(
            issueCodes({
                ...baseBundle(),
                rawIndex: {modes: [{...VALID_INDEX.modes[0], weights: "lookup_other.csv"}]},
            }),
        ).toContain("stakeengine-import-mode-weights-filename-mismatch");
    });

    it("reports stakeengine-import-csv-missing/stakeengine-import-books-missing when a mode's files are absent", () => {
        expect(issueCodes({...baseBundle(), modeFiles: [{...VALID_MODE_FILES, csvFileExists: false}]})).toContain("stakeengine-import-csv-missing");
        expect(issueCodes({...baseBundle(), modeFiles: [{...VALID_MODE_FILES, booksFileExists: false}]})).toContain("stakeengine-import-books-missing");
    });

    it("reports stakeengine-import-csv-malformed-row for a row that isn't exactly 3 comma-separated integer fields", () => {
        expect(issueCodes({...baseBundle(), modeFiles: [{...VALID_MODE_FILES, csvLines: ["0,1"]}]})).toContain("stakeengine-import-csv-malformed-row");
        expect(issueCodes({...baseBundle(), modeFiles: [{...VALID_MODE_FILES, csvLines: ["a,b,c"]}]})).toContain("stakeengine-import-csv-malformed-row");
    });

    it("reports stakeengine-import-books-malformed-line for a books line that isn't {id, events, payoutMultiplier}-shaped", () => {
        expect(issueCodes({...baseBundle(), modeFiles: [{...VALID_MODE_FILES, bookLines: [{foo: 1}]}]})).toContain("stakeengine-import-books-malformed-line");
    });

    it("reports stakeengine-import-outcome-id-not-integer for a non-canonical CSV id or a negative book line id", () => {
        expect(issueCodes({...baseBundle(), modeFiles: [{...VALID_MODE_FILES, csvLines: ["01,1,0"]}]})).toContain("stakeengine-import-outcome-id-not-integer");
        expect(
            issueCodes({
                ...baseBundle(),
                modeFiles: [
                    {
                        ...VALID_MODE_FILES,
                        bookLines: [{id: -1, events: [{index: 0, type: "reveal", board: [["A"]]}, {index: 1, type: "finalWin", amount: 0, payoutMultiplier: 0}], payoutMultiplier: 0}],
                    },
                ],
            }),
        ).toContain("stakeengine-import-outcome-id-not-integer");
    });

    it("reports stakeengine-import-outcome-weight-not-positive-integer for a zero or negative weight", () => {
        expect(issueCodes({...baseBundle(), modeFiles: [{...VALID_MODE_FILES, csvLines: ["0,0,0"]}]})).toContain(
            "stakeengine-import-outcome-weight-not-positive-integer",
        );
    });

    it("reports stakeengine-import-csv-books-count-mismatch when the CSV and books have different row/line counts", () => {
        expect(
            issueCodes({
                ...baseBundle(),
                modeFiles: [{...VALID_MODE_FILES, csvLines: ["0,1,0", "1,1,0"]}],
            }),
        ).toContain("stakeengine-import-csv-books-count-mismatch");
    });

    it("reports stakeengine-import-csv-books-id-set-mismatch when an id exists on only one side", () => {
        expect(
            issueCodes({
                ...baseBundle(),
                modeFiles: [{...VALID_MODE_FILES, csvLines: ["1,1,0"]}],
            }),
        ).toContain("stakeengine-import-csv-books-id-set-mismatch");
    });

    it("reports stakeengine-import-csv-books-payout-multiplier-mismatch when the same id disagrees between CSV and books", () => {
        expect(
            issueCodes({
                ...baseBundle(),
                modeFiles: [{...VALID_MODE_FILES, csvLines: ["0,1,5"]}],
            }),
        ).toContain("stakeengine-import-csv-books-payout-multiplier-mismatch");
    });

    it("reports stakeengine-import-outcome-count-mismatch when the manifest's outcomeCount disagrees with the actual row/line count", () => {
        expect(
            issueCodes({
                ...baseBundle(),
                rawManifest: {...VALID_MANIFEST, modes: [{...VALID_MANIFEST.modes[0], outcomeCount: 5}]},
            }),
        ).toContain("stakeengine-import-outcome-count-mismatch");
    });
});
