/**
 * Reviewed, static inputs and outputs for the portable runtime parity fixture.
 * Values are deliberately not generated by the WASM implementation under test.
 */
export const PORTABLE_RUNTIME_GOLDEN = {
    id: "portable-runtime-golden",
    seed: "wasm-parity-golden",
    commands: [{bet: 1}, {bet: 1}, {bet: 1}],
    continuationCommand: {bet: 1},
    replayRound: 4,
    expected: {
        draws: [0.5967806649859995, 0.5375500756781548, 0.07866769284009933, 0.3642472343053669, 0.5574665090534836, 0.0013346921186894178],
        rounds: [
            {sequence: 1, draw: 0.5967806649859995, stops: [1, 1], screen: [["B"], ["B"]], winMultiplier: 1, stake: 1, payout: 1, creditsBefore: 1000, credits: 1000, command: {bet: 1}},
            {sequence: 2, draw: 0.07866769284009933, stops: [0, 0], screen: [["A"], ["A"]], winMultiplier: 2, stake: 1, payout: 2, creditsBefore: 1000, credits: 1001, command: {bet: 1}},
            {sequence: 3, draw: 0.5574665090534836, stops: [1, 0], screen: [["B"], ["A"]], winMultiplier: 0, stake: 1, payout: 0, creditsBefore: 1001, credits: 1000, command: {bet: 1}},
        ],
        state: {schemaVersion: "pokie.state.v1", seed: "wasm-parity-golden", draws: [0.5967806649859995, 0.5375500756781548, 0.07866769284009933, 0.3642472343053669, 0.5574665090534836, 0.0013346921186894178], sequence: 3, credits: 1000, rngState: 1365295755},
        continuation: {sequence: 4, draw: 0.14641731861047447, stops: [0, 1], screen: [["A"], ["B"]], winMultiplier: 0, stake: 1, payout: 0, creditsBefore: 1000, credits: 999, command: {bet: 1}},
        replay: {round: 4, totalBet: 4, totalWin: 3, screen: [["A"], ["B"]]},
    },
} as const;

/** A separate reviewed wild/scatter fixture; it must never reuse base-game draws or outputs. */
export const PORTABLE_RUNTIME_FEATURE_GOLDEN = {
    id: "portable-runtime-feature-golden",
    seed: "wasm-feature-parity-golden",
    commands: [{bet: 1}, {bet: 1}, {bet: 1}],
    continuationCommand: {bet: 1},
    replayRound: 4,
    fixture: {
        reelStrips: [["S", "W", "A"], ["A", "S", "W"]],
        wilds: ["W"],
        scatters: ["S"],
        paytable: {A: {2: 2}, W: {2: 3}, S: {2: 4}},
    },
    expected: {
        draws: [0.5218852667603642, 0.30686308699660003, 0.5139746307395399, 0.07492379867471755, 0.2316682490054518, 0.5898979792837054],
        rounds: [
            {sequence: 1, draw: 0.5218852667603642, stops: [1, 0], screen: [["W"], ["A"]], winMultiplier: 2, stake: 1, payout: 2, creditsBefore: 1000, credits: 1001, command: {bet: 1}},
            {sequence: 2, draw: 0.5139746307395399, stops: [1, 0], screen: [["W"], ["A"]], winMultiplier: 2, stake: 1, payout: 2, creditsBefore: 1001, credits: 1002, command: {bet: 1}},
            {sequence: 3, draw: 0.2316682490054518, stops: [0, 1], screen: [["S"], ["S"]], winMultiplier: 4, stake: 1, payout: 4, creditsBefore: 1002, credits: 1005, command: {bet: 1}},
        ],
        state: {schemaVersion: "pokie.state.v1", seed: "wasm-feature-parity-golden", draws: [0.5218852667603642, 0.30686308699660003, 0.5139746307395399, 0.07492379867471755, 0.2316682490054518, 0.5898979792837054], sequence: 3, credits: 1005, rngState: 1485312856},
        continuation: {sequence: 4, draw: 0.7555967909283936, stops: [2, 0], screen: [["A"], ["A"]], winMultiplier: 2, stake: 1, payout: 2, creditsBefore: 1005, credits: 1006, command: {bet: 1}},
        replay: {round: 4, totalBet: 4, totalWin: 10, screen: [["A"], ["A"]]},
    },
} as const;

/** Production line evaluation rejects all-wild lines; retain this as an explicit portable parity case. */
export const PORTABLE_RUNTIME_ALL_WILD_GOLDEN = {
    id: "portable-runtime-all-wild-golden",
    seed: "wasm-all-wild-golden",
    commands: [{bet: 1}],
    continuationCommand: {bet: 1},
    replayRound: 2,
    fixture: {
        reelStrips: [["W"], ["W"]],
        wilds: ["W"],
        scatters: [],
        paytable: {W: {2: 3}},
    },
    expected: {screen: [["W"], ["W"]], payout: 0, credits: 999},
} as const;
