import {SymbolsSequence, SymbolsSequenceDescribing} from "pokie";

// Fixed, hand-chosen reel strips (one of every base-game symbol per reel; no wild) -- the golden-value
// tests in this directory need every spin's *screen* to be exactly reproducible given a seed, which
// VideoSlotConfig's default reel strips are not: they're generated by ReelsSymbolsSequencesGenerator
// using unseeded randomness, so two VideoSlotConfig instances never share the same strips. Mirrors the
// fixed sequences already used for the RTP simulation in DefaultGameSessionSimulation.test.ts.
export function goldenVideoSlotSymbolsSequences(): SymbolsSequenceDescribing<string>[] {
    return [
        new SymbolsSequence().fromArray(["J", "9", "Q", "10", "A", "S", "K"]),
        new SymbolsSequence().fromArray(["K", "S", "10", "A", "9", "Q", "J"]),
        new SymbolsSequence().fromArray(["J", "Q", "10", "9", "S", "A", "K"]),
        new SymbolsSequence().fromArray(["Q", "10", "9", "S", "K", "A", "J"]),
        new SymbolsSequence().fromArray(["Q", "A", "J", "10", "9", "S", "K"]),
    ];
}
