import fs from "fs";
import {readRecognizedStakeEngineManifest} from "./readRecognizedStakeEngineManifest.js";

// StakeEngineExporter now replaces its whole output directory atomically (build into a fresh temp sibling
// directory, then swap it into place — see StakeEngineExporter.swapDirectoryIntoPlace) so that a re-export never
// leaves a mode's now-removed CSV/books lying around. That makes "which specific filenames are about to be
// written" the wrong question to ask beforehand: the entire existing directory is about to be discarded, not
// just a few paths within it. So this checks *directory-level* ownership instead: refuses to touch an existing,
// non-empty outDir unless it's recognized as a prior "pokie stakeengine export" run's own output (via that run's
// own pokie-manifest.json) — otherwise a caller pointing --out at an unrelated directory by mistake would have
// it silently wiped. An empty (or nonexistent) directory is always safe to replace — there's nothing to lose.
export function assertSafeToReplaceStakeEngineExportDirectory(outDir: string): void {
    let destination: fs.Stats;
    try {
        // lstat is intentional. A link is not a POKIE-owned container even
        // when its target happens to contain a recognizable manifest: writing
        // through it would let an --out path escape its caller's namespace.
        destination = fs.lstatSync(outDir);
    } catch (error) {
        if ((error as NodeJS.ErrnoException).code === "ENOENT") return;
        throw error;
    }
    if (destination.isSymbolicLink()) {
        throw new Error(`"${outDir}" is a symbolic link, not a POKIE-owned Stake Engine output directory. Choose a different --out directory.`);
    }
    if (!destination.isDirectory()) {
        throw new Error(`"${outDir}" already exists and is not a directory. Choose a different --out directory or remove it first.`);
    }
    if (fs.readdirSync(outDir).length === 0) {
        return;
    }

    if (readRecognizedStakeEngineManifest(outDir) === undefined) {
        throw new Error(
            `"${outDir}" already exists and was not generated by "pokie stakeengine export" (no recognized pokie-manifest.json). ` +
                "Refusing to replace it wholesale — choose a different --out directory, empty it first, or point --out at a directory " +
                'previously produced by "pokie stakeengine export".',
        );
    }
}
