// ============================================================================
// GENERATED FILE — do not hand-edit.
//
// Produced by "pokie build" from a GameBlueprint JSON config. Re-run "pokie build" (see this
// package's README.md) to regenerate this file after changing the blueprint; any manual edits here
// are overwritten on the next run.
//
// Game: P6-10 Finite Slot (id: "p6-10-finite-slot", version 1.0.0)
// Generated by: pokie 1.3.0
// ============================================================================

import type {GameBlueprint, PokieGameContext} from "pokie" with { "resolution-mode": "require" };

// ---------------------------------------------------------------------------
// pokie runtime
// ---------------------------------------------------------------------------
const {
    CustomLinesDefinitions,
    ReelsSymbolsSequencesGenerator,
    SeededRandomNumberGenerator,
    SymbolsCombinationsGenerator,
    SymbolsSequence,
    VideoSlotConfig,
    VideoSlotSession,
    VideoSlotSessionSerializer,
    computeGameBlueprintHash,
} = require("pokie");

// ---------------------------------------------------------------------------
// Blueprint data (embedded verbatim from the source GameBlueprint JSON config)
// ---------------------------------------------------------------------------
const blueprint: GameBlueprint = {
    "manifest": {
        "id": "p6-10-finite-slot",
        "name": "P6-10 Finite Slot",
        "version": "1.0.0"
    },
    "reels": 2,
    "rows": 1,
    "symbols": [
        "A",
        "B"
    ],
    "paytable": {
        "A": {
            "2": 5
        }
    },
    "reelStrips": [
        [
            "A",
            "A",
            "B"
        ],
        [
            "A",
            "B"
        ]
    ]
};

// ---------------------------------------------------------------------------
// VideoSlotConfig assembly
//
// Setter order matters here: setAvailableBets/setWildSymbols/setScatterSymbols must run before
// setAvailableSymbols, which rebuilds the paytable and (absent explicit reel strips) the default
// reel sequences from whatever wilds/scatters are set at that point. The paytable, paylines, and
// reel strips are set after setAvailableSymbols, since it would otherwise overwrite them. See
// VideoSlotConfig for the full contract.
//
// "context" (present only to read context.seed) makes every random choice this function itself makes
// -- VideoSlotConfig's own default reel-strip shuffle (absent explicit reelStrips/symbolWeights) and
// the symbolWeights branch's own shuffle() below -- deterministic for a given seed, the same as
// createSession's own combinationsGenerator (see the "combinationsGeneratorDeclaration" this function
// is called from). A blueprint with literal blueprint.reelStrips needs none of this: it never calls
// shuffle() at all.
// ---------------------------------------------------------------------------
function createConfig(context?: PokieGameContext) {
    const reelStripRng = context && context.seed !== undefined ? new SeededRandomNumberGenerator(context.seed) : undefined;
    const config = new VideoSlotConfig(undefined, reelStripRng ? new ReelsSymbolsSequencesGenerator(reelStripRng) : undefined);

    if (blueprint.availableBets) {
        config.setAvailableBets(blueprint.availableBets);
    }
    config.setReelsNumber(blueprint.reels);
    config.setReelsSymbolsNumber(blueprint.rows);
    config.setWildSymbols(blueprint.wilds || []);
    config.setScatterSymbols(blueprint.scatters || []);
    config.setAvailableSymbols(blueprint.symbols);

    const paytable = config.getPaytable();
    for (const symbolId of Object.keys(blueprint.paytable)) {
        const payouts = blueprint.paytable[symbolId];
        for (const times of Object.keys(payouts)) {
            paytable.setPayoutForSymbol(symbolId, Number(times), payouts[times]);
        }
    }

    if (blueprint.paylines) {
        const linesDefinitions = new CustomLinesDefinitions();
        blueprint.paylines.forEach((line, index) => linesDefinitions.setLineDefinition(String(index), line));
        config.setLinesDefinitions(linesDefinitions);
    }

    if (blueprint.reelStrips) {
        config.setSymbolsSequences(blueprint.reelStrips.map((strip) => new SymbolsSequence().fromArray(strip)));
    } else if (blueprint.symbolWeights) {
        const sequences: unknown[] = [];
        for (let i = 0; i < blueprint.reels; i++) {
            sequences.push(new SymbolsSequence().fromNumbersOfSymbols(blueprint.symbolWeights).shuffle(reelStripRng));
        }
        config.setSymbolsSequences(sequences);
    }

    return config;
}

// ---------------------------------------------------------------------------
// PokieGame contract (see docs/game-packages.md)
// ---------------------------------------------------------------------------
module.exports = {
    getManifest() {
        return blueprint.manifest;
    },
    createSession(context?: PokieGameContext) {
        const config = createConfig(context);
        const combinationsGenerator = context && context.seed !== undefined
            ? new SymbolsCombinationsGenerator(config, new SeededRandomNumberGenerator(context.seed))
            : new SymbolsCombinationsGenerator(config);
        return new VideoSlotSession(config, combinationsGenerator);
    },
    getSessionSerializer() {
        return new VideoSlotSessionSerializer();
    },
    getConfigHash() {
        return computeGameBlueprintHash(blueprint);
    },
    createExactEnumerationSession(combinationsGenerator: unknown) {
        const config = createConfig();
        return new VideoSlotSession(config, combinationsGenerator);
    },
};
