import fs from "fs";
import path from "path";

const RECOGNIZED_GENERATORS = new Set(["pokie outcomelibrary build", "pokie stakeengine import"]);

/** Direct bundle publication may replace only a canonical POKIE container. */
export function assertSafeToReplaceOutcomeLibraryBundleDirectory(outDir: string): void {
    let destination: fs.Stats;
    try {
        destination = fs.lstatSync(outDir);
    } catch (error) {
        if ((error as NodeJS.ErrnoException).code === "ENOENT") return;
        throw error;
    }

    if (destination.isSymbolicLink()) {
        throw new Error(`"${outDir}" is a symbolic link, not a POKIE-owned Outcome Library output directory. Choose a different output directory.`);
    }
    if (!destination.isDirectory()) {
        throw new Error(`"${outDir}" already exists and is not a directory. Choose a different output directory or remove it first.`);
    }
    try {
        const manifest = JSON.parse(fs.readFileSync(path.join(outDir, "manifest.json"), "utf-8")) as {generatedBy?: unknown};
        if (typeof manifest.generatedBy === "string" && RECOGNIZED_GENERATORS.has(manifest.generatedBy)) return;
    } catch {
        // Empty/malformed directories are intentionally unproven.
    }
    throw new Error(
        `"${outDir}" already exists and was not generated by "pokie outcomelibrary build" (no recognized manifest.json). ` +
        "Refusing to replace it wholesale — choose a different output directory or point at a directory previously produced by " +
        '"pokie outcomelibrary build".',
    );
}
