import assert from "node:assert/strict";
import {createHash} from "node:crypto";
import {mkdir, mkdtemp, readFile, rm, writeFile} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {test} from "@jest/globals";
import {P805_PERSONAS, P805_REQUIRED_EVIDENCE_KINDS, P805_REQUIRED_OBSERVATIONS, P805_SCHEMA_VERSION, validateP805ProductReadinessCampaign} from "../../scripts/p8-05-product-readiness-campaign.mjs";

const initial = {candidateId:"1".repeat(40), candidatePackageSha256:"a".repeat(64)}, retest = {candidateId:"2".repeat(40), candidatePackageSha256:"b".repeat(64)};
const hash = (value) => createHash("sha256").update(value).digest("hex"); const stamp = (offset) => new Date(Date.parse("2026-09-19T20:00:00.000Z") + offset).toISOString();
const rendered = {execution:"packed-public-cli-built-studio-rendered-controls", viewports:["wide", "narrow"], consoleExceptions:0, unhandledRequestFailures:0, documentOverflow:false, inaccessiblePrimaryActions:0, unexplainedDisabledControls:0, recovery:{reloadReconnect:true, projectSwitch:true, staleResponseIsolation:true, unsavedWorkProtection:true, serverRestart:true}, jobs:{success:true, actionableFailure:true, cooperativeCancellation:true, retryWithoutPartialArtifacts:true}};
const timings = {startupMs:1, projectCreationMs:1, validationMs:1, buildMs:1, simulationMs:1, replayMs:1, cancellationMs:1};

async function campaignFixture() {
    const directory = await mkdtemp(path.join(os.tmpdir(), "pokie-p8-05-campaign-")); let sequence = 0;
    const evidence = async (candidate, kind, at) => { const contents = `P8-05 bounded ${kind} ${++sequence}\n`; const relativePath = `records/${sequence}.txt`; await mkdir(path.join(directory, "records"), {recursive:true}); await writeFile(path.join(directory, relativePath), contents); return {evidenceId:`e-${sequence}`, path:relativePath, sha256:hash(contents), sizeBytes:Buffer.byteLength(contents), capturedAt:at, kind, ...candidate}; };
    const audit = async (persona, phase, candidate, offset) => { const artifacts = []; for (const [index, kind] of P805_REQUIRED_EVIDENCE_KINDS.entries()) artifacts.push(await evidence(candidate, kind, stamp(offset + 2 + index))); return {auditId:`${phase}-${persona}`, persona, phase, ...candidate, startedAt:stamp(offset), endedAt:stamp(offset + 40), cleanContext:{workspace:`/tmp/p8-05-${phase}-${persona}-work`, configurationRoot:`/tmp/p8-05-${phase}-${persona}-config`, browserProfile:`/tmp/p8-05-${phase}-${persona}-profile`, reused:false}, observations:P805_REQUIRED_OBSERVATIONS[persona], timings, rendered, evidence:artifacts}; };
    const initialAudits = []; for (const [index, persona] of P805_PERSONAS.entries()) initialAudits.push(await audit(persona, "initial", initial, 100 + index * 100)); const retests = []; for (const [index, persona] of P805_PERSONAS.entries()) retests.push(await audit(persona, "retest", retest, 1000 + index * 100));
    const finding = {id:"F-1", severity:"P2", material:true, persona:"ui-ux", publicSurface:"Studio Simulation", reproducer:"Run then cancel", owner:"cli/studio", status:"resolved", evidence:await evidence(initial, "finding", stamp(700))};
    const write = async (name, value) => writeFile(path.join(directory, name), `${JSON.stringify(value, null, 2)}\n`);
    const initialRecord = {schemaVersion:P805_SCHEMA_VERSION, campaignId:"p8-05-fixture", audits:initialAudits}; await write("PROVENANCE.json", {schemaVersion:P805_SCHEMA_VERSION, campaignId:"p8-05-fixture", startedAt:stamp(1), cleanRoomAttestation:"I recorded each initial persona audit before reading prior findings, source, fixes, or prior campaign evidence.", initialCandidate:initial}); await write("initial-audits.json", initialRecord);
    const frozen = {schemaVersion:P805_SCHEMA_VERSION, campaignId:"p8-05-fixture", ...initial, frozenAt:stamp(800), findings:[finding]}; const anchor = path.join(path.dirname(directory), `${path.basename(directory)}-freeze.json`); frozen.externalAnchor = {path:anchor, sha256:"0".repeat(64), anchoredAt:stamp(850)}; const {externalAnchor, ...frozenPayload} = frozen; const frozenContents = `${JSON.stringify(frozenPayload, null, 2)}\n`; const anchorContents = `${JSON.stringify({campaignId:"p8-05-fixture", ...initial, initialAuditsSha256:hash(`${JSON.stringify(initialRecord, null, 2)}\n`), frozenFindingsSha256:hash(frozenContents), appendOnly:true, anchoredAt:stamp(850)})}\n`; await writeFile(anchor, anchorContents); frozen.externalAnchor.sha256 = hash(anchorContents); await write("frozen-findings.json", frozen);
    await write("finding-register.json", {schemaVersion:P805_SCHEMA_VERSION, campaignId:"p8-05-fixture", findings:[finding]}); await write("regressions.json", {schemaVersion:P805_SCHEMA_VERSION, campaignId:"p8-05-fixture", regressions:[{findingId:"F-1", testPath:"tests/cli/studio-client/src/P805ValeraPersonas.browser.test.tsx", commitId:retest.candidateId, candidatePackageSha256:retest.candidatePackageSha256, result:"passed", verifiedAt:stamp(900), assertions:["cancelled job has no report"]}]}); await write("retests.json", {schemaVersion:P805_SCHEMA_VERSION, campaignId:"p8-05-fixture", startedAt:stamp(950), audits:retests}); const uiux = retests.find((entry) => entry.persona === "ui-ux"); await write("closeout.json", {schemaVersion:P805_SCHEMA_VERSION, campaignId:"p8-05-fixture", ...retest, closedAt:stamp(1700), releaseReady:true, appendOnly:true, cleanup:{noOwnedProcessesRemain:true, failedOrCancelledArtifactsRemoved:true}, dispositions:[{findingId:"F-1", status:"resolved", retestAuditId:uiux.auditId, retestEvidenceId:uiux.evidence[0].evidenceId}]});
    return {directory, async cleanup() { await rm(directory, {recursive:true, force:true}); await rm(anchor, {force:true}); }};
}
test("requires every evidence kind, external freeze, unique contexts, final-candidate regression and persona retest", async () => { const fixture = await campaignFixture(); try { assert.equal((await validateP805ProductReadinessCampaign(fixture.directory, retest)).candidateId, retest.candidateId); } finally { await fixture.cleanup(); } });
test("fails closed on mutable chronology and context claims", async () => { const fixture = await campaignFixture(); try { const file = path.join(fixture.directory, "retests.json"), value = JSON.parse(await readFile(file, "utf8")); value.audits[0].cleanContext.workspace = value.audits[1].cleanContext.workspace; await writeFile(file, `${JSON.stringify(value)}\n`); await assert.rejects(() => validateP805ProductReadinessCampaign(fixture.directory, retest), /reuses a clean context/i); } finally { await fixture.cleanup(); } });
